// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {PoolKey} from "../types/PoolKey.sol";
import {PoolId} from "../types/PoolId.sol";
import {BalanceDelta} from "../types/BalanceDelta.sol";
import {Slot0} from "../types/Slot0.sol";
import {Currency} from "../types/Currency.sol";
import {IVault} from "./IVault.sol";
import {IPoolEvents} from "../events/IPoolEvents.sol";

/**
 * @title IPoolManager
 * @notice Core singleton interface for managing SupaDex AMM pools.
 */
interface IPoolManager is IPoolEvents {
    /**
     * @notice Struct holding parameters for modifying liquidity in a pool.
     */
    struct ModifyLiquidityParams {
        int24 tickLower;
        int24 tickUpper;
        int256 liquidityDelta;
        bytes32 salt;
    }

    /**
     * @notice Struct holding parameters for executing a swap in a pool.
     */
    struct SwapParams {
        bool zeroForOne;
        int256 amountSpecified;
        uint160 sqrtPriceLimitX96;
    }

    /**
     * @notice Returns the underlying Vault contract.
     */
    function vault() external view returns (IVault);

    /**
     * @notice Initializes a new AMM pool.
     * @param key The immutable pool parameters.
     * @param sqrtPriceX96 The initial square root price.
     * @param hookData Arbitrary data passed to plugin/hook during initialization.
     * @return tick The initial tick corresponding to sqrtPriceX96.
     */
    function initialize(PoolKey memory key, uint160 sqrtPriceX96, bytes calldata hookData) external returns (int24 tick);

    /**
     * @notice Adds or removes liquidity from a pool.
     * @param key The pool identifier key.
     * @param params Liquidity change parameters.
     * @param hookData Arbitrary data passed to plugin/hook.
     * @return callerDelta BalanceDelta of the caller's transient delta.
     * @return feesAccrued BalanceDelta of fees collected.
     */
    function modifyLiquidity(PoolKey memory key, ModifyLiquidityParams memory params, bytes calldata hookData)
        external
        returns (BalanceDelta callerDelta, BalanceDelta feesAccrued);

    /**
     * @notice Executes a swap against a pool.
     * @param key The pool identifier key.
     * @param params Swap parameters (direction, amount, price limit).
     * @param hookData Arbitrary data passed to plugin/hook.
     * @return swapDelta The net token delta generated by the swap.
     */
    function swap(PoolKey memory key, SwapParams memory params, bytes calldata hookData)
        external
        returns (BalanceDelta swapDelta);

    /**
     * @notice Donates tokens directly to active in-range liquidity providers.
     * @param key The pool identifier key.
     * @param amount0 Amount of token0 to donate.
     * @param amount1 Amount of token1 to donate.
     * @param hookData Arbitrary data passed to plugin/hook.
     * @return delta Net token delta from donation.
     */
    function donate(PoolKey memory key, uint256 amount0, uint256 amount1, bytes calldata hookData)
        external
        returns (BalanceDelta delta);

    /**
     * @notice Returns the current Slot0 state for a pool.
     */
    function getSlot0(PoolId id) external view returns (Slot0);

    /**
     * @notice Returns the total active liquidity for a pool.
     */
    function getLiquidity(PoolId id) external view returns (uint128);

    /**
     * @notice Returns accrued uncollected protocol fees for a currency.
     */
    function protocolFeesAccrued(Currency currency) external view returns (uint256);

    /**
     * @notice Sets the protocol fee take rate for a pool (owner only).
     */
    function setProtocolFee(PoolKey memory key, uint24 protocolFee) external;

    /**
     * @notice Collects accrued protocol fees to a recipient (fee controller only).
     */
    function collectProtocolFees(Currency currency, address recipient, uint256 amount)
        external
        returns (uint256 collected);
}
